### PR TITLE
Bracket WAI middleware spans with detachContext

### PR DESCRIPTION
**Pull request by velveteer**
After updating to `hs-opentelemetry-instrumentation-wai-0.1.0.0`, I noticed our Datadog APM traces were starting to group unrelated requests together. Notably all of these sporadic groups shared the same GHC thread ID.

Further investigation led me to this commit: https://github.com/iand675/hs-opentelemetry/commit/34569fc8a92189011cadeda757375847efc92ef7. At first glance, removing this `bracket` would seem harmless, assuming each WAI request is served by a separate thread. But in fact `warp` uses some heuristics to enable the HTTP keep-alive optimization, which means a single thread can serve multiple requests. Without detaching the context from the thread after serving a request, the initial request context is re-used for subsequent requests, which means propagated OTel context will be inherited by those request spans.

I tested this small patch in our production application and it appears to have resolved our APM woes.

### CODE REVIEW

**Comment by velveteer** [comment]
I believe that stripping W3C Trace Context headers can mask this issue. Which makes me wonder if this is related to https://www.iankduncan.com/articles/2023-08-28-opentelemetry-gotchas-phantom-spans.

**Comment by iand675** [comment]
Can you rebase this against `main`? I think this change makes sense and would like to merge it.

**Comment by velveteer** [comment]
Not sure if you were notified but I rebased this.

**Review by michaelpj — APPROVED** [review]
This makes sense, but please record the explanation from the PR in a comment, so future people will know what's going on.

**Comment by velveteer** [comment]
Thanks @michaelpj. I've updated the commit message and added a code comment co-located with the change.

**Comment by michaelpj** [comment]
Thanks!

**Pull request merged**
